# This code is an example GitHub Actions workflow for deploying a Node.js/Express application to Google Cloud Platform (GCP) using a Docker-compose.

# name: The name of the workflow.
name: Deploy to Google cloud platform

# on: Indicates when this workflow should run. In this case, it runs when a commit is pushed to the main branch.
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

permissions:
  id-token: write
  contents: read


# env: Defines environment variables to be used throughout the workflow.
env:
  PROJECT_ID: "note-sharing-390521"
  IMAGE_NAME: "Shahi-Notes-Image"
  CONTAINER_NAME: "shahi-notes-container"
  REGION: "asia-south1"
  SERVICE_NAME: "Shahi_Notes-service"
  REPOSITORY_NAME: "shahi-notes"
  PORT: 8000
  TAG: latest

# jobs: Defines the work to be done by this workflow.
jobs:
  integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint code
        run: echo "Linting repository"

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18-alpine3.15'
      
      - name: Install dependencies
        run: |
          npm ci
          
      - name: Run tests
        run: |
          npm test

  build-and-push-image:
    name: Continuous Delivery
    needs: integration
    runs-on: ubuntu-latest
    steps:
      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
    
      # Build and push Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.CONTAINER_NAME }}:${{ env.TAG }}
          builder: |
            docker buildx create --use --name=mybuilder
            docker buildx build \
              --platform linux/amd64,linux/arm64 \
              --load \
              --tag ${{ env.CONTAINER_NAME }}:${{ env.TAG }} \
              --tag ${{ env.CONTAINER_NAME }}:latest \
              .
      
      # Authenticate with GCP using a service account
      - name: Configure gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_email: "note-sharing@note-sharing-390521.iam.gserviceaccount.com"
          service_account_key: ${{ secrets.SECRET_KEY }}
          export_default_credentials: true
      
      # Configure Docker Credential Helper for Artifact Registry
      - name: Configure Docker Credential Helper for Artifact Registry
        run: |
          gcloud auth configure-docker asia-south1-docker.pkg.dev
      
      - name: Push Docker Image to Artifact Registry
        run: |
          docker push asia-south1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY_NAME }}:${{ env.TAG }}

      - name: Echo Image Name
        run: |
          echo "Pushed Docker image asia-south1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY_NAME }}:${{ env.TAG }}"

  
  Continuous-Deployment:
    needs: build-and-push-image
    runs-on: self-hosted
    steps:
      - name: Pull Latest Docker Image from artifact-registry
        run: |
          docker pull asia-south1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}/${{ env.TAG }}


      - name: Stop and Remove Previous Container
        run: |
          docker stop ${{ env.CONTAINER_NAME }} || true
          docker rm ${{ env.CONTAINER_NAME }} || true

      - name: Run Docker Image
        run: |
          docker run -dp ${{ env.PORT }}:${{ env.PORT }} --name ${{ env.CONTAINER_NAME }} gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}

      - name: Clean Previous Images and Containers
        run: |
          docker image prune -f
          docker container prune -f

  #  The job involved 
  #   - pulling the latest Docker image, 
  #   - removing and stopping any previous containers that were running, 
  #   - running the new Docker image to serve users, and 
  #   - cleaning up any previous images and containers.




# This code is an example GitHub Actions workflow for deploying a Node.js/Express application to Google Cloud Platform (GCP) using a Docker image. Here's a description of what each component of the code does:

# name: The name of the workflow.
# on: Indicates when this workflow should run. In this case, it runs when a commit is pushed to the main branch.
# env: Defines environment variables to be used throughout the workflow.
# jobs: Defines the work to be done by this workflow. In this case, there is only one job.
# build_and_deploy: The name of the job.
# runs-on: The type of machine to run this job on. In this case, it will run on an ubuntu-latest machine.
# steps: Defines the steps that the job should take.
# name: The name of the step.
# uses: GitHub provides a number of pre-built actions to simplify common tasks, such as checking out code, installing dependencies, authenticating to services, and more. This step uses the actions/checkout@v2 action to check out the code.
# run: Runs a series of commands on the machine. In this case, it installs the dependencies required for the application.
# run: Builds a Docker image for the application using the Dockerfile in the root of the project.
# name: The name of the step.
# uses: Another pre-built action provided by GitHub that sets up GCP credentials for the job to authenticate to GCP.
# with: Defines the inputs to the setup-gcloud action, including the GCP project ID and the service account key used to authenticate to GCP.
# run: Pushes the Docker image to the Google Container Registry (GCR) using the gcloud CLI. This step also tags the image as the latest version.
# uses: An action that deploys the app to Cloud Run using the Docker image.
# with: Defines the inputs to the cloud-run-deploy action, including the Cloud Run service name, the Docker image used to deploy the app, the GCP region where the app is deployed, and the no-traffic flag to ensure the newly deployed revision does not receive any traffic until explicitly promoted.


 